version: "3"
services:

  postgres-db:
    restart: always
    image: ghusta/postgres-world-db:2.4
    ports:
      - "5432:5432"
    environment:
      - DB_USER=world
      - DB_PASS=world123
      - DB_NAME=world-db

  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - postgres-db
